# Generated by Django 5.1.5 on 2025-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_safaribooking_remove_hotel_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('5-star', '5-Star'), ('4-star', '4-Star'), ('3-star', '3-Star')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
