# Generated by Django 5.1.5 on 2025-01-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.JSONField(default='y'),
            preserve_default=False,
        ),
    ]
