# Generated by Django 5.1.5 on 2025-01-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hotel_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='videos',
        ),
    ]
