# Generated by Django 5.1.5 on 2025-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_hotel_facilities_remove_hotel_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('room_type', models.CharField(choices=[('Deluxe Room', 'Deluxe Room'), ('Luxury Villa', 'Luxury Villa'), ('Premium Cottage', 'Premium Cottage')], max_length=50)),
                ('additional_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
