# Generated by Django 5.1.5 on 2025-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_check_in_booking_check_out_booking_form_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Deluxe Room', 'Deluxe Room'), ('Luxury Villa', 'Luxury Villa'), ('Premium Cottage', 'Premium Cottage')], max_length=50, null=True),
        ),
    ]
