# Generated by Django 5.1.5 on 2025-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_booking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='safari_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='safari_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
