# Generated by Django 5.1.5 on 2025-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
